spring.application.name=Shop

# PostgreSQL connection properties
spring.datasource.url=jdbc:postgresql://localhost:5433/UserServiceDb
spring.datasource.username=postgres
spring.datasource.password=1234
