package com.example.Shop.controllers;

import com.example.Shop.dto.StaffDTO;
import com.example.Shop.entities.Staff;
import com.example.Shop.services.StaffService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.server.ResponseStatusException;

import java.util.List;

@CrossOrigin(origins = "http://localhost:5173")
@RestController
@RequestMapping("/api/staff")
public class StaffController {

    @Autowired
    private StaffService staffService;

    @GetMapping
    public List<StaffDTO> getAllStaff() {
        return staffService.getAllStaff();
    }

    @GetMapping("/{id}")
    public StaffDTO getWorkerById(@PathVariable Long id) {
        var worker = staffService.getWorkerById(id);
        if (worker == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Worker with ID " + id + " not found");
        }
        return worker;
    }

    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public StaffDTO createWorker(@RequestBody Staff staff) {
        // Inside request body, the ID should not be set, as it will be generated by the database
        return staffService.createWorker(staff);
    }

    @PutMapping("/{id}")
    public StaffDTO updateWorker(@PathVariable Long id, @RequestBody Staff staff) {
        StaffDTO updatedWorker = staffService.updateWorker(id, staff);
        if (updatedWorker == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Can not update: worker with ID " + id + " is not found");
        }
        return updatedWorker;
    }

    @DeleteMapping("/{id}")
    public void deleteWorker(@PathVariable Long id) {
        boolean deleted = staffService.deleteWorker(id);
        if (!deleted) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Worker with ID " + id + " is already deleted or not found");
        }
    }
}
