package com.example.Shop.dto;

import lombok.Data;
import java.math.BigDecimal;

@Data
public class StaffKPIDTO {
    private Long staffId;
    private String fullName;
    private BigDecimal totalRevenue; // Total revenue generated by the staff member
    private long salesCount;         // Number of sales made by the staff member
    private BigDecimal averageCheck; // Average check amount for the staff member
    private Double kpiScore;         // Final KPI score calculated based on the above metrics
}